## install

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [2]:
! pip install hmmlearn

     |████████████████████████████████| 374 kB 7.6 MB/s 


In [28]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from hmmlearn import hmm,base
from sklearn import preprocessing
import math

#implement model

## encode

In [4]:
le = preprocessing.LabelEncoder()
le.fit(['hot', 'cold'])

LabelEncoder()

In [5]:
le.classes_

array(['cold', 'hot'], dtype='<U4')

In [6]:
le.transform(['hot', 'hot', 'cold'])

array([1, 1, 0])

In [7]:
le.inverse_transform([1, 1, 0])

array(['hot', 'hot', 'cold'], dtype='<U4')

##State

In [8]:
states = ["hot", "cold"]
n_states = len(states)
le = preprocessing.LabelEncoder()
le.fit(states)

LabelEncoder()

##observation for train

In [9]:
X1 = np.array([3,3,2])
X2 = np.array([1,1,2])
X3 = np.array([1,2,3])

X = np.concatenate([X1.reshape(3,1), X2.reshape(3,1),X3.reshape(3,1)])
lengths = [len(X1), len(X2),len(X3)]

##Multinomial HMM 

###inital model

In [10]:
startprob = np.array([1/3,2/3])
tranprob = np.array([[1/3,2/3],[1/3,2/3]])

In [11]:
Multi = hmm.MultinomialHMM(n_components=2,n_iter=10,random_state=100)

In [12]:
Multi.fit(X,lengths)

MultinomialHMM(algorithm='viterbi', init_params='ste', n_components=2,
               n_iter=10, params='ste',
               random_state=RandomState(MT19937) at 0x7F3494A06490,
               startprob_prior=1.0, tol=0.01, transmat_prior=1.0,
               verbose=False)

In [13]:
Multi.monitor_.converged

True

In [14]:
Multi.n_features

4

In [15]:
Multi.transmat_

array([[0.24521003, 0.75478997],
       [0.00170301, 0.99829699]])

In [16]:
Multi.emissionprob_

array([[0.00000000e+00, 7.06963478e-01, 8.78575580e-05, 2.92948664e-01],
       [0.00000000e+00, 3.81979847e-02, 5.96568303e-01, 3.65233713e-01]])

###observation for test

In [18]:
ob = np.array([1,2,3]).reshape(3,1)
ob

array([[1],
       [2],
       [3]])

### predict

In [24]:
Multi.decode(ob)

(-2.15513421881006, array([0, 1, 1], dtype=int32))

In [19]:
Multi.predict(ob)

array([0, 1, 1], dtype=int32)

In [20]:
le.inverse_transform(Multi.predict(ob))

array(['cold', 'hot', 'hot'], dtype='<U4')

In [21]:
Multi.predict_proba(ob)

array([[9.99888566e-01, 1.11434488e-04],
       [4.55307033e-05, 9.99954469e-01],
       [1.37576835e-03, 9.98624232e-01]])

In [32]:
Multi.score(ob)

-2.153609888064929